[theme]
#primary accent color for interactive elements
primaryColor = "#d33682"

#Background color for the main content area
backgroundColor = "#DFEBF6"

#Background color used for the sidebar 
secondaryBackgroundColor = "#ADD8E6"

#Color used for almost all text
textColor = "#000000"